### Add new user
POST http://localhost:3000/auth/register/
content-type: application/json

{
    "name": "matti", 
    "email": "matti@email.com", 
    "password": "masa123"
}

### Get authenticated user's info
GET http://localhost:3000/auth/me
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTM1MTAwMDgwLCJleHAiOjE1MzUxMDA2ODB9.pAii2RD5OOl8mAu0lT6PRKQMU4SXxHw3AtJ7IR6DvTE

### Login user
POST http://localhost:3000/auth/login/
content-type: application/json

{
    "email": "matti@email.com", 
    "password": "masa123"
}

### Try to login with wrong email
POST http://localhost:3000/auth/login/
content-type: application/json

{
    "email": "esko@email.com", 
    "password": "masa123"
}

### Logout
GET http://localhost:3000/auth/logout/