@id = 6

### Get all values
GET http://localhost:3000/students/

### Get value by id
GET http://localhost:3000/students/{{id}}

### Get values with under 100 credits
GET http://localhost:3000/students/under100

### Create new student value
POST http://localhost:3000/students/
content-type: application/json

{
    "surename": "Puolikuu", 
    "forename": "Veli", 
    "studentnumber": "r9191", 
    "credits": 12
}

### Update student value
PUT http://localhost:3000/students/{{id}}
content-type: application/json

{
    "surename": "Puolikuu", 
    "forename": "Veli", 
    "studentnumber": "r9191", 
    "credits": 201
}

### Delete value
DELETE http://localhost:3000/students/{{id}}
