@id = 6
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNTM1MzUzNTg4LCJleHAiOjE1MzUzNTQxODh9.IoqJ13GgBC9OdYMsNkIO8GDXg2J8JNwY6RXwP0FQt7Y

### Get all values
GET http://localhost:3000/students/

### Get value by id
GET http://localhost:3000/students/{{id}}

### Get values with under 100 credits
GET http://localhost:3000/students/under100

### Create new student value
POST http://localhost:3000/students/
content-type: application/json
x-access-token: {{token}}

{
    "surname": "Puolikuu", 
    "forename": "Veli", 
    "studentnumber": "r9191", 
    "credits": 12
}

### Update student value
PUT http://localhost:3000/students/{{id}}
content-type: application/json
x-access-token: {{token}}

{
    "surname": "Puolikuu", 
    "forename": "Veli", 
    "studentnumber": "r9191", 
    "credits": 201
}

### Delete value
DELETE http://localhost:3000/students/{{id}}
x-access-token: {{token}}
